export const sliderItems = [
    {
        id: 1,
        img: "https://i.ibb.co/cXFnLLV/3.png",
        title: "SUMMER SALE",
        desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
        bg: "f5fafd",
        
    },
    {
        id: 2,
        img: "https://i.ibb.co/cXFnLLV/3.png",
        title: "AUTUMN COLLECTION",
        desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
        bg: "fcf1ed",
       
    },
    {
        id: 3,
        img: "https://i.ibb.co/cXFnLLV/3.png",
        title: "LOUNGEWEAR LOVE",
        desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
        bg: "fbf0f4",
        categoryName : "shirt",
    },
];

export const categories = [
    {
        id: 1,
        img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        title: "SHIRT STYLE!",
        categoryName: "coat",
    },
    {
        id: 2,
        img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        title: "LOUNGEWEAR LOVE",
        categoryName: "sweater",
    },
    {
        id: 3,
        img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        title: "LIGHT JACKETS",
        categoryName: "shirt",
    },
];

export const popularProducts = [
    {
        id: 1,
        img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
        name : "JAKE GUITAR VINTAGE CRUSHER TEE",
        color: "black",
        size: "XL",
        count : 1,
        price : 40,
    },
    {
        id: 2,
        img: "https://cdn.pixabay.com/photo/2016/11/23/06/57/isolated-t-shirt-1852114__340.png",
        name : "ANGELA NATURAL TEE",
        color: "blue",
        size: "XL",
        count : 1,
        price : 50,
    },
    {
        id: 3,
        img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
        name : "VINTAGE BAG",
        color: "brown",
        size: "L",
        count : 1,
        price : 20,
    },
    {
        id: 4,
        img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
        name : "BUS PAT BURTE",
        color: "black",
        size: "XL",
        count : 1,
        price : 70,
    },
    {
        id: 5,
        img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
        name : "NOISSUE X CREATESY TOTE BAG",
        color: "brown",
        size: "20",
        count : 1,
        price : 30,
    },
    {
        id: 6,
        img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
        name : "ROCKET VINTAGE CHILL CAP",
        color: "darkgreen",
        size: "L",
        count : 1,
        price : 20,
    },
    {
        id: 7,
        img: "https://cdn.pixabay.com/photo/2017/09/03/14/41/mock-up-2710535__340.jpg",
        name : "NOISSUE X CREATESY TOTE BAG",
        color: "brown",
        size: "20",
        count : 1,
        price : 30,
    },
    {
        id: 8,
        img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
        name : "WOMEN JACKET",
        color: "brown",
        size: "20",
        count : 1,
        price : 70,
    },
    {
        id: 9,
        img: "https://cdn.pixabay.com/photo/2016/11/23/06/57/isolated-t-shirt-1852113__340.png",
        name : "WOMEN JACKET",
        color: "brown",
        size: "20",
        count : 1,
        price : 70,
    },
    {
        id: 10,
        img: "https://cdn.pixabay.com/photo/2019/02/13/19/23/t-shirt-3995093__340.png",
        name : "MEN'S SWEATERS",
        color: "brown",
        size: "20",
        count : 1,
        price : 70,
    },
    {
        id: 11,
        img: "https://cdn.pixabay.com/photo/2014/04/03/10/55/t-shirt-311732__340.png",
        name : "WOMEN JACKET",
        color: "brown",
        size: "20",
        count : 1,
        price : 70,
    },
    {
        id: 12,
        img: "https://cdn.pixabay.com/photo/2013/07/13/14/08/apparel-162192__340.png",
        name : "WOMEN JACKET",
        color: "brown",
        size: "20",
        count : 1,
        price : 70,
    },
    {
        id: 13,
        img: "https://media.istockphoto.com/photos/black-leather-pants-picture-id515139983?b=1&k=20&m=515139983&s=170667a&w=0&h=aa81f8-GrsO4lh2r6xDQk0cj3mUhw0TetBNI0WCvq2s=",
        name : "MEN'S JEANS ",
        color: "brown",
        size: "20",
        count : 1,
        price : 70,
    },
    {
        id: 14,
        img: "https://cdn.pixabay.com/photo/2013/07/13/14/07/apparel-162180__340.png",
        name : "WOMEN JACKET",
        color: "brown",
        size: "20",
        count : 1,
        price : 70,
    },
    {
        id: 15,
        img: "https://cdn.pixabay.com/photo/2017/06/12/08/07/male-2394718__340.jpg",
        name : "WOMEN JACKET",
        color: "brown",
        size: "20",
        count : 1,
        price : 70,
    },
]


export const carts = [
    {
        id: 1,
        img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
        name: "JESSIE THUNDER SHOES",
        color: "black",
        size: "37.5",
        price: 40,
        count: 1,
    },
    {
        id: 3,
        img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
        name: "JESSIE THUNDER SHOES",
        color: "black",
        size: "37.5",
        price: 40,
        count: 1,
    },
    {
        id: 2,
        img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
        name: "JESSIE THUNDER SHOES",
        color: "black",
        size: "37.5",
        price: 40,
        count: 1,
    },
]